import { Service } from 'types/service';
export const dummyServices: Service[] = [
  {
    image: {
      imageUrl:
        'https://res.cloudinary.com/dve9vmjzv/image/upload/v1601223495/hodw7szs41mbj8yiabbe.png',
      imageId: 'placeholder',
    },
    id: {
      original: '11',
      pretty: 'loading11',
    },
    nameLT: 'Kraunasi...',
    nameEN: 'Loading...',
    labelLT: '...',
    labelEN: '...',
    shortDescriptionLT: '',
    shortDescriptionEN: '',
    descriptionLT: '',
    descriptionEN: '',
    price: 0,
    priceDescriptionLT: '',
    priceDescriptionEN: '',
    benefitsTitleLT: '',
    benefitsTitleEN: '',
    benefitsDescriptionLT: '',
    benefitsDescriptionEN: '',
    benefits: [],
  },
  {
    image: {
      imageUrl:
        'https://res.cloudinary.com/dve9vmjzv/image/upload/v1601223495/hodw7szs41mbj8yiabbe.png',
      imageId: 'placeholder',
    },
    id: {
      original: '22',
      pretty: 'loading22',
    },
    nameLT: 'Kraunasi...',
    nameEN: 'Loading...',
    labelLT: '...',
    labelEN: '...',
    shortDescriptionLT: '',
    shortDescriptionEN: '',
    descriptionLT: '',
    descriptionEN: '',
    price: 0,
    priceDescriptionLT: '',
    priceDescriptionEN: '',
    benefitsTitleLT: '',
    benefitsTitleEN: '',
    benefitsDescriptionLT: '',
    benefitsDescriptionEN: '',
    benefits: [],
  },
  {
    image: {
      imageUrl:
        'https://res.cloudinary.com/dve9vmjzv/image/upload/v1601223495/hodw7szs41mbj8yiabbe.png',
      imageId: 'placeholder',
    },
    id: {
      original: '33',
      pretty: 'loading33',
    },
    nameLT: 'Kraunasi...',
    nameEN: 'Loading...',
    labelLT: '...',
    labelEN: '...',
    shortDescriptionLT: '',
    shortDescriptionEN: '',
    descriptionLT: '',
    descriptionEN: '',
    price: 0,
    priceDescriptionLT: '',
    priceDescriptionEN: '',
    benefitsTitleLT: '',
    benefitsTitleEN: '',
    benefitsDescriptionLT: '',
    benefitsDescriptionEN: '',
    benefits: [],
  },
];
